config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about', to: 'pages#about'
  
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories

    validates :title, presence:true, length: { minimum:3, maximum:40}
    validates :description, presence:true, length: { minimum:3, maximum:200}
    validates :user_id, presence:true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
    
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :article_categories
    has_many :articles, through: :article_categories

    validates :name, presence: true, 
    uniqueness: {case_sensitive: false}, 
    length: {minimum:3, maximum:20}


end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase}

    validates :user, presence: true, 
    uniqueness: {case_sensitive: false}, 
    length: {minimum:3, maximum:20}

    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
    uniqueness: {case_sensitive: false},
    format: {with: EMAIL_REGEX}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in for this."
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :find_article, only:[:edit, :update, :show, :destroy]
    
    def index
        @articles = Article.paginate(page: params[:page], per_page:5)
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(get_params)
        @article.user = User.find(session[:user_id])
        if @article.save
            flash[:success] = "Article created succesfully"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def update
        if @article.update(get_params)
            flash[:success] = "Article updated succesfully"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def show
    end
    
    def destroy
        @article.destroy
        flash[:success] = "Article deleted succesfully"
        redirect_to articles_path
    end

    private
        def get_params
            params.require(:article).permit(:title, :description, category_ids:[])
        end

        def find_article
            @article = Article.find(params[:id])
        end

    
        
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :require_admin, except:[:index,:show]

    def new
        @category = Category.new
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category created"
            redirect_to categories_path
        else
            render 'new'
        end    
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Category updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end   
    end
    
   
    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? && !current_user.admin)
            flash[:danger] = "Action only for admins"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to articles_path if logged_in?
    end

    def about
        
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if !user.nil? && user.authenticate(params[:session][:password])
            puts "User found"
            session[:user_id] = user.id
            flash[:success] = "Logged in successfully"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Bad credentials"
            render 'new'
        end
    end

   
    def destroy
        session[:user_id] = nil
        flash[:success] = "Logged out successfully"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only:[:edit, :update, :show]
    before_action :require_admin, only:[:destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Hello #{@user.user}!"
            redirect_to user_path(@user)
        else
            render ('new')
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Account Updated Successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page:5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page:5)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:succes] = "User and user's articles deleted."
        redirect_to users_path
    end

    private
    def user_params
        params.require(:user).permit(:user,:email,:password)
    end

    def find_user
        @user = User.find(params[:id])
    end

    def require_admin
        if logged_in? && !current_user.admin?
            flash[:danger] = "You must be an admin for this"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for user
        gravatar_id = Digest::MD5::hexdigest(user.email)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=100"
        image_tag(gravatar_url, alt:"User Avatar", class: "img-thumbnail")
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

<div class = "container">
    
    <div class="row">
        <div class="col">
        </div>
    </div>

    <div class="row">
        <div class="col center">
            <div class="card card-body bg-light">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
            </div>

            <% if article.categories.any? %>
            <p>Categories: 
            <% article.categories.each do |category| %>
                <span class="badge"> <%= link_to category.name, category_path(category) %>  </span>
            <% end %>
            </p>          
            <% end %>
        
            <div class="article-metadata">
                <small>
                Created by: <%= article.user.user if article.user %>, 
                <%= time_ago_in_words(article.created_at)%> ago. 
                Updated: <%= time_ago_in_words(article.updated_at)%> ago. 
                </small>
            </div>

            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <div class="article-actions">
                    <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-md btn-primary" %>
                    <%= link_to "Delete this article", article_path(article), method: :delete,
                                        data: { confirm: "Are you sure you want to delete the article?"},
                                        class: "btn btn-xs btn-danger" %>
                </div>
            <% end %>

        </div>
    </div>

    </div>

    <div class="row">
        <div class="col">
        </div>
    </div>

</div>
<br>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>

<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |a| %>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= a.label :title %>
  </div>
  <div class="col-sm-8">
    <%= a.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= a.label :description %>
  </div>
  <div class="col-sm-8">
    <%= a.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <div class="col-sm-offset-2 col-sm-8">
      <%= a.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
  </div>
</div>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= a.submit class: 'btn btn-primary btn-lg' %>
  </div>
</div>

<% end %>

<%= link_to 'All articles', articles_path %>

app/views/articles/edit.html.erb
<h1>Update your article</h1>

<% if logged_in? && (@article.user == current_user || current_user.admin)%>
    <%= render 'form'%>
<% else %>

<% flash.now[:danger] = "You are not the owner of the article" %>
     
<% end %>

app/views/articles/index.html.erb
<h1 class="center">Listing all articles</h1>

<div class = "digg_pagination ">
    <%= will_paginate @articles %>
</div>


<%= render 'article', obj: @articles %>


<div class = "digg_pagination ">
    <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="container-fluid">
    <h1>Create your article</h1>
    <%= render 'form'%>
</div>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class = "container">
    
    <div class="row">
        <div class="col">
        </div>
    </div>

    <div class="row">
        <div class="col center">
        <div class = "card bg-light">
            <div class="card-title article-title">
                Description:
            </div>

            <div class="card-body">
                <%= simple_format(@article.description) %>
            </div>

        <% if @article.categories.any? %>
            <p>Categories: 
            <% @article.categories.each do |category| %>
                <span class="badge"> <%= link_to category.name, category_path(category) %>  </span>
            <% end %>
            </p>          
        <% end %>
        
        <div class="article-actions">
            <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
                <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete this article", article_path(@article), method: :delete,
                            data: { confirm: "Are you sure you want to delete the article?"},
                            class: "btn btn-xs btn-danger" %>
            <% end %>
            <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
        </div>
        </div>
    </div>

    </div>

    <div class="row">
        <div class="col">
        </div>
    </div>

</div>

<br>

<div class = "container">
    
    <div class="row">
        <div class="col">
        </div>
    </div>

    <div class="row">
        <div class="col center">
            <div class="card card-body bg-light">
                <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                <div class="article-title">
                <%= link_to @article.user.user , user_path(@article.user) %>
                </div>
            <div class="article-body">
            <small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
            </div>
        </div>
    </div>

    </div>

    <div class="row">
        <div class="col">
        </div>
    </div>

</div>

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj:@category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |a| %>

<div class="form-group">
<div class="control-label col-sm-2">
    <%= a.label :name %>
</div>
<div class="col-sm-8">
    <%= a.text_field :name, class: "form-control", placeholder:"Category's name", autofocus: true %>
</div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <%= a.submit "Create", class: 'btn btn-primary btn-lg'%>
    </div>
</div>

<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>

<%= render 'form' %>

<%= link_to 'All articles', articles_path %>

app/views/categories/index.html.erb
<h1 align="center">Listing Categories</h1>

<div class = "digg_pagination ">
    <%= will_paginate @categories %>
</div>

<% @categories.each do |category| %>

<div class = "container">
    
    <div class="row">
        <div class="col">
        </div>
    </div>

    <div class="row">
        <div class="col center">
            <div class="card card-body bg-light">
                <div class="article-title">
                    <%= link_to category.name, category_path(category) %>
                </div>

            <% if logged_in? && current_user.admin? %>
                <div class="article-actions">
                    <%= link_to "Rename", edit_category_path(category), class: "btn btn-xs btn-danger" %>
                </div>
            <% end %>

        </div>
    </div>

    </div>

    <div class="row">
        <div class="col">
        </div>
    </div>

</div>
<br>
<% end %>

<div class = "digg_pagination ">
    <%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create Category</h1>

<%= render 'shared/errors', obj:@category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |a| %>

<div class="form-group">
<div class="control-label col-sm-2">
    <%= a.label :name %>
</div>
<div class="col-sm-8">
    <%= a.text_field :name, class: "form-control", placeholder:"Category's name", autofocus: true %>
</div>
</div>

<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
    <%= a.submit "Create", class: 'btn btn-primary btn-lg'%>
</div>
</div>

<% end %>


<%= link_to 'All articles', articles_path %>

app/views/categories/show.html.erb
<h1 class="center">Category: <%= @category.name %> </h1>

<div class = "digg_pagination ">
    <%= will_paginate @category_articles %>
</div>


<%= render '/articles/article', obj: @category_articles %>


<div class = "digg_pagination ">
    <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<footer class="blockquote-footer">by Gabriel Monzon, </footer>

app/views/layouts/_messages.html.erb
<div class="text-center">
    <div class="col-md-10 col-md-offset-1">
        <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">×</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
        <% end %>
    </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Alpha Blog', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Articles', articles_path, class:"nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to 'Users', users_path, class:"nav-link"%>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'New Article', new_article_path, class:"dropdown-item" %>
          </div>
        </li>
      <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path, class:"dropdown-item" %>
            <% Category.all.each do |category| %>
              <%= link_to category.name, category_path(category), class:"dropdown-item" %>
            <% end %>
            <% if logged_in? && current_user.admin %>
              <div class="dropdown-divider"></div>
              <%= link_to "Create Category", new_category_path, class:"dropdown-item" %>
            <% end %>
          </div>
        </li>
        <li class="nav-item active">
          <%= link_to 'About', about_path, class:"nav-link"%>
        </li>

      </ul>

      <ul class="navbar-nav">
      <% if logged_in? %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.admin %>
              Admin
            <% end %>
            Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'View profile', user_path(current_user), class:"dropdown-item" %>
            <%= link_to 'Edit profile', edit_user_path(current_user), class:"dropdown-item" %>
          </div>
        </li>

        <li class="nav-item active">
          <%= link_to 'Logout', logout_path, method: :delete, class:"nav-link"%>
        </li>

      <% else %>
        <li class="nav-item active">
          <%= link_to 'Login', login_path, class:"nav-link"%>
        </li>
        <li class="nav-item active">
          <%= link_to 'Signup', signup_path, class:"nav-link"%>
        </li>
          
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
    <%= render 'layouts/nav'%>

    <%= render 'layouts/messages'%>
    
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
</html>

app/views/pages/about.html.erb
<h3 align="center">Created by: Gabriel Monzon, gabriel.monsa39@gmail.com </h3>

app/views/pages/home.html.erb
<div class="container-fluid jumbotron center bg-dark text-white">
  <h1 class="display-4">Alpha Blog!</h1>
  <p class="lead">Alpha Blog is awesome.</p>
  <p class="lead">
    <%= link_to('Join', signup_path, class:"btn btn-primary btn-lg bg-dark") %>
  </p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row container">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="card card-body bg-danger">
                <div class="card-title">
                    <h2 class="panel-title">
                    <%= pluralize(obj.errors.count, "error") %>
                    prohibited this article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |a| %>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= a.label :user %>
  </div>
  <div class="col-sm-8">
    <%= a.text_field :user, class: "form-control", autofocus: true %>
  </div>
</div>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= a.label :email %>
  </div>
  <div class="col-sm-8">
    <%= a.email_field :email, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= a.label :password %>
  </div>
  <div class="col-sm-8">
    <%= a.password_field :password, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= a.submit(@user.new_record? ? "Signup!" : "Update Account", class: 'btn btn-primary btn-lg' )%>
  </div>
</div>

<% end %>

<%= link_to 'All articles', articles_path %>

app/views/users/edit.html.erb
<h1 align="center">Update Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="center">Listing all users</h1>


<div class = "digg_pagination ">
    <%= will_paginate @users %>
</div>

<% @users.each do |user| %>

<div class = "container">
    
    <div class="row">
        <div class="col">
        </div>
    </div>

    <div class="row">
        <div class="col center">
            <div class="card card-body bg-light">
                <%= link_to gravatar_for(user), user_path(user) %>
                <div class="article-title">
                <%= link_to user.user , user_path(user) %>
                </div>
            <div class="article-body">
            <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
            </div>
            <% if logged_in? && current_user.admin %>
              <%= link_to "Delete user", user_path(user), method: :delete, 
                    data: {confirm: "Delete user and user's articles? "} %>
            <% end %>
        </div>
    </div>

    </div>

    <div class="row">
        <div class="col">
        </div>
    </div>

</div>

<br>
<% end %>


<div class = "digg_pagination ">
    <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h1 align="center">Create Account</h1>

<%= render 'shared/errors', obj:@user %>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.user %>'s page</h1>

<div class = "center">
    <%= gravatar_for @user%> 
</div>

<br>

<div class = "digg_pagination ">
    <%= will_paginate @articles %>
</div>

<%= render 'articles/article', obj: @articles %>

<div class = "digg_pagination ">
    <%= will_paginate @articles %>
</div>